# Generated by Django 4.1 on 2022-08-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directors',
            name='name',
        ),
        migrations.AddField(
            model_name='directors',
            name='first_name',
            field=models.CharField(blank=True, help_text='Nombre del director:', max_length=64),
        ),
        migrations.AddField(
            model_name='directors',
            name='last_name',
            field=models.CharField(blank=True, help_text='Apellidos director:', max_length=64),
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Introduce el titulo de la película:', max_length=64)),
                ('description', models.CharField(help_text='Descripción:', max_length=255)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.directors')),
            ],
        ),
    ]
